[general]
import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[env]
TERM = "xterm-256color"
#TERM = "alacritty-direct"

[window]
padding.x = 10
padding.y = 10
dimensions.lines = 40
dimensions.columns = 100

decorations = "Buttonless"

opacity = 1.0
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 13
