# ~/.ticker.yaml
show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
#show-holdings: true
interval: 5
currency: USD
currency-summary-only: false
sort: user
watchlist:
  - ^DJI
  - ^SPX
  - AMZN
  - VT
  - VTI
  - VXUS
  - SCHD
  - VEA
  - VWO
  - USRT
  - BND
  - TIP
